version: "3.5"

services:
  postgres:
    image: postgres:11-alpine
    container_name: metadata
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metadatadb
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: metadata-pgadmin    
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"

volumes:
  postgres:
  pgadmin: