# Generated by Django 3.2.7 on 2022-03-15 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('type_resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('describe', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type_resource.typesource')),
            ],
        ),
    ]
