# Generated by Django 3.2.7 on 2022-03-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='typesource',
            table='type_resource',
        ),
    ]
